keys:
  - &primary age1zteescyshskm3n35s23875vjj2358zkejtcyxaeah5p46q4xk5qqjq2nzt
  - &yubikey-jayne age1yubikey1qgd5kj7y87zlqpgww0y75ged7cr87uksfnpj9weyc4h66y2luv3vgz9rr6l
  # &yubikey-inara will be added once inara's YubiKey is set up
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *primary
          - *yubikey-jayne